# name: real_estate_flutter
# description: The Project CEO Panel (Real Estate MVP)
# publish_to: "none"
# version: 0.1.0+1

# environment:
#   sdk: ">=3.3.0 <4.0.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   http: ^1.2.2
#   flutter_secure_storage: ^9.2.2
#   provider: ^6.1.1
#   shared_preferences: ^2.2.2
#   intl: ^0.19.0
#   go_router: ^17.0.1
#   file_picker: ^8.1.4
#   image_picker: ^1.1.2
#   dropdown_button2: ^2.3.9

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^4.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/

#   flutter:
#     sdk: flutter
#   fl_chart: ^0.65.0
name: real_estate_flutter
description:  The Project CEO Panel (Real Estate MVP)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage:  ^9.2.2
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  go_router: ^17.0.1
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/